-- Hal Yönetim Sistemi - Supabase veritabanı şeması
-- Supabase Dashboard > SQL Editor içinde bu dosyayı çalıştırın.

create table if not exists public.halciler (
  id bigint generated by default as identity primary key,
  ad text not null,
  soyad text not null,
  email text not null unique,
  sifre text not null,
  vergi_numarasi text not null unique,
  telefon text,
  adres text,
  sirket_adi text,
  kayit_tarihi date default current_date,
  aktif boolean default true
);

create table if not exists public.ciftciler (
  id bigint generated by default as identity primary key,
  halci_id bigint references public.halciler(id) on delete set null,
  ad_soyad text not null,
  telefon text,
  adres text,
  tc_kimlik text,
  kayit_tarihi date default current_date,
  aktif boolean default true,
  notlar text
);

create table if not exists public.urunler (
  id bigint generated by default as identity primary key,
  ciftci_id bigint references public.ciftciler(id) on delete cascade,
  urun_adi text not null,
  urun_tipi text,
  miktar numeric,
  birim text,
  fiyat numeric,
  gelis_tarihi date,
  son_kullanim_tarihi date,
  kalite text,
  notlar text,
  durum text default 'Beklemede'
);

create table if not exists public.satislar (
  id bigint generated by default as identity primary key,
  halci_id bigint references public.halciler(id) on delete cascade,
  ciftci_id bigint references public.ciftciler(id) on delete set null,
  urun_id bigint references public.urunler(id) on delete set null,
  urun_adi text,
  miktar numeric,
  birim text,
  fiyat numeric,
  kalite text,
  birim_fiyat numeric,
  toplam_tutar numeric,
  satis_tarihi date,
  satis_saati text,
  durum text,
  alici_halci_id bigint references public.halciler(id) on delete set null,
  alici_sirket_adi text,
  fiyat_teklifi numeric,
  satici_fiyati numeric,
  sirket_adi text,
  sirket_telefon text,
  sirket_adres text,
  sirket_vergi_no text,
  tarih timestamptz default now()
);

create table if not exists public.talepler (
  id bigint generated by default as identity primary key,
  alici_halci_id bigint references public.halciler(id) on delete cascade,
  alici_halci_ad_soyad text,
  alici_sirket_adi text,
  alici_sirket_telefon text,
  alici_sirket_adres text,
  alici_sirket_vergi_no text,
  satici_halci_id bigint references public.halciler(id) on delete cascade,
  satici_halci_ad_soyad text,
  satici_sirket_adi text,
  urun_id bigint references public.urunler(id) on delete set null,
  urun_adi text,
  urun_tipi text,
  kalite text,
  miktar numeric,
  birim text,
  birim_fiyat numeric,
  fiyat_teklifi numeric,
  toplam_tutar numeric,
  notlar text,
  durum text default 'Beklemede',
  talep_tarihi date,
  talep_saati text,
  onay_tarihi date,
  onay_saati text
);

create index if not exists idx_ciftciler_halci_id on public.ciftciler(halci_id);
create index if not exists idx_urunler_ciftci_id on public.urunler(ciftci_id);
create index if not exists idx_satislar_halci_id on public.satislar(halci_id);
create index if not exists idx_talepler_satici_halci_id on public.talepler(satici_halci_id);
create index if not exists idx_talepler_alici_halci_id on public.talepler(alici_halci_id);

alter table public.halciler enable row level security;
alter table public.ciftciler enable row level security;
alter table public.urunler enable row level security;
alter table public.satislar enable row level security;
alter table public.talepler enable row level security;

-- Geliştirme için açık erişim politikaları.
-- Üretimde Supabase Auth ile kısıtlayın.
-- drop if exists: schema.sql tekrar çalıştırıldığında "already exists" hatasını önler
drop policy if exists "halciler_all" on public.halciler;
drop policy if exists "ciftciler_all" on public.ciftciler;
drop policy if exists "urunler_all" on public.urunler;
drop policy if exists "satislar_all" on public.satislar;
drop policy if exists "talepler_all" on public.talepler;

create policy "halciler_all" on public.halciler for all using (true) with check (true);
create policy "ciftciler_all" on public.ciftciler for all using (true) with check (true);
create policy "urunler_all" on public.urunler for all using (true) with check (true);
create policy "satislar_all" on public.satislar for all using (true) with check (true);
create policy "talepler_all" on public.talepler for all using (true) with check (true);
